class TrainConfig:
    def __init__(self,
                 dataset_name="wb14123/couplet",
                 max_samples=50000,
                 valid_ratio=0.05,
                 max_len=32,
                 batch_size=64,
                 d_model=256,
                 nhead=8,
                 num_encoder_layers=3,
                 num_decoder_layers=3,
                 dim_feedforward=512,
                 embed_size=256,
                 hidden_size=512,
                 dropout=0.1,
                 epochs=15,
                 learning_rate=0.0003,
                 teacher_forcing_ratio=0.7,
                 beam_width=5,
                 repetition_penalty=1.2,
                 no_repeat_ngram_size=2,
                 seed=42,
                 save_path="outputs/model.pt"):
        self.dataset_name = dataset_name
        self.max_samples = max_samples
        self.valid_ratio = valid_ratio
        self.max_len = max_len
        self.batch_size = batch_size
        self.d_model = d_model
        self.nhead = nhead
        self.num_encoder_layers = num_encoder_layers
        self.num_decoder_layers = num_decoder_layers
        self.dim_feedforward = dim_feedforward
        self.embed_size = embed_size
        self.hidden_size = hidden_size
        self.dropout = dropout
        self.epochs = epochs
        self.learning_rate = learning_rate
        self.teacher_forcing_ratio = teacher_forcing_ratio
        self.beam_width = beam_width
        self.repetition_penalty = repetition_penalty
        self.no_repeat_ngram_size = no_repeat_ngram_size
        self.seed = seed
        self.save_path = save_path